### ISSUE TITLE
Update splice scenario

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/AdInsertion#22]
See inline

**Comment by haudiobe** [comment]
addressed in latest version, please check clause 1.1.1.5 https://1drv.ms/w/s!AiNJEPgowJnWgddH3qMKzknnTw9FBg

**Comment by technogeek00** [comment]
In general seems fine, it may be good to detail that these splice points are where downstream components may decide to insert / replace ads.

Additional question around this line:
> The reason and details of each splice point and the conditions may be carried through but are irrelevant for the media preparation

Should this be "...the conditions **should** be carried through..." since we want this data coming out of the encoder over IF-1. Having this as a should would align with our assumptions in the IF-1 section.

**Comment by technogeek00** [comment]
Number of additional comments within the Word Doc that should be addressed as well

**Comment by technogeek00** [comment]
Thomas has provided updates to address this awhile ago, closing tracked change.
