### ISSUE TITLE
Specify a single way to things unless very good reasons exist

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/AdInsertion#43]
Specifications that leave the door open for multiple ways to implement things do not achieve the maximum level of interoperability possible. There should only be multiple ways to do things if there are substantial differences and those differences are explained in the guideliens ("do X if A, do Y if B").

The ad insertion CR currently seems very open ended in various ways. For example, should packager make periods or leave it to the manipulator? It says both are valid options. This will just lead to incompatible implementations. Pick one choice and stick with it. If both options seem valid, it is fine for this choice to be arbitrary - the end result is still better than offering a choice with no clear rationale on why/when/what to choose.

IOP does not need to cover all possible implementation options. Quite contrary, we need to specify one single interpretation that we consider is good for general use. People can always make non-IOP-conforming implementations if they feel their scenario is sufficiently unique to deviate. The only choices IOP should offer are choices driven by differences in the use cases, not differences in implementations.

I admit I am not familiar with the logic behind these possible implementation options (and am unable to derive the logic in part due to #39), so the example I picked above is arbitrary (there seem to be quite a few examples to choose from). Perhaps offering this particular choice is entirely justified. Though even then, this justification should certainly be added to the text, describing not only the options but when to choose which option.

**Comment by haudiobe** [comment]
The ad insertion CR currently seems very open ended in various ways. For example, should packager make periods or leave it to the manipulator? It says both are valid options. This will just lead to incompatible implementations. Pick one choice and stick with it. If both options seem valid, it is fine for this choice to be arbitrary - the end result is still better than offering a choice with no clear rationale on why/when/what to choose.

_The basic idea is that the packager provides Periods as ad insertion opportunities. The MPD proxy then can do the following: (i) leave Period in (ii) remove Period (iii) replace Period. This should be written more clearly._ 

IOP does not need to cover all possible implementation options. Quite contrary, we need to specify one single interpretation that we consider is good for general use. People can always make non-IOP-conforming implementations if they feel their scenario is sufficiently unique to deviate. The only choices IOP should offer are choices driven by differences in the use cases, not differences in implementations.

I admit I am not familiar with the logic behind these possible implementation options (and am unable to derive the logic in part due to #39), so the example I picked above is arbitrary (there seem to be quite a few examples to choose from). Perhaps offering this particular choice is entirely justified. Though even then, this justification should certainly be added to the text, describing not only the options but when to choose which option.

_we should also add justification for choices_

**Comment by haudiobe** [comment]
addressed in community review
