### ISSUE TITLE
Comments on 1.2.3.

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#55]
Is a reference not sufficient for this section ? What about other playback platforms (especially legacy ones). Can this section be shortened and can there be some sentence about support for other platforms ? Should not any DASH player be able to playback the streams with ads inserted, would that not be a better goal ?

**Comment by technogeek00** [comment]
At first read the additional specification can seem over stated, but considering the larger context of the splice conditions and the requirements a player must typically meet to achieve seamless playout in these workflows I think it is informative to explicitly call out the pieces. My only worry is omitting a requirement and having this list treated as stand-alone instead of a basis.

Ideally any DASH player would be able to playback an ad stream, but attempting to tailor the ad insertion doc to all existing players would provide us a lowest common denominator approach. I believe with this document we are trying to standardize best practices for an optimal playout experience of an ad supported stream which requires raising the implementation bar requirement of players today.

**Comment by haudiobe** [comment]
(AdIn 19/11/08) No specific issue, wait for detailed comments.

**Comment by haudiobe** [comment]
(AdIn 19/11/22) No comments received - close issue
