### ISSUE TITLE
Check against IOP 4.3

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/AdInsertion#62]
we need to check against what is in IOP 4.3 in ad insertion and embed missing things in the current CR in the right sections.

**Comment by technogeek00** [comment]
I'll take the task of detailed comparison

**Comment by technogeek00** [comment]
I've collected a set of comparisons after a detailed re-reading of IOP v4.3 Clause 5 (4.3 Text) and the latest Ad Insertion CR (CR Text), but generally the CR text either meets or exceeds the specification of the 4.3 text. As expected the CR text heavily changes the structure of information to isolate interfaces within the ad insertion workflow and describe the interface implementations and interactions, but in doing so the previously existing information from 4.3 is mostly ported where appropriate (see table for caveats). The most significant difference is the omission of remote element resolution as we have simplified SSAI to better match common industry deployments and will bring remote elements back with proper guidelines / restrictions as part of the SGAI architecture work.

| Information Category | 4.3 Text | CR Text | Needs Followup? |
|---|---|---|:-:|
| General MPD processing semantics | The 4.3 Text generally repeated and re-referenced a lot around the processing of MPDs, Period Timing, and DASH Events | As part of the CR Text we have consciously removed this repeated information and directly referenced the other portions of the IOP and active CRs that directly address these subjects. Where further assumptions/restrictions are necessary for ad insertion they are explicitly stated | No |
| MPD Updates | The 4.3 Text heavily relies on `emsg` for MPD validity signalling and because of this talks a lot about MPD Update semantics. | Again we have generally deferred to the proper MPD update text where necessary, but the CR text has been significantly rewritten to avoid `emsg` box usage and instead explicitly calls out usage of `MPD@minimumUpdatePeriod` with a value set such that it is effective for the known minimum splice insert time (1.2.4) | No |
| High-Level Workflows/Architectures | The 4.3 Text structure lends to repetition between the _server-based_ and _app-based_ architectures, even though the interoperability section (5.6) states _app-based_ is not part of the document! General scenarios are embedded as workflows in individual architectures making them harder to find. | The CR text explicitly pulls the scenarios and architectures up. SSAI and SGAI defined as in-scope, CSAI is not explicitly called out as out of scope | Addressing absence of CSAI |
| Scenario Coverage | The 4.3 text is very detailed about linear workflows and refers on-demand workflows to leverage linear like as well. | The CR text parallels this and acknowledges linear as primary concern with more on-demand details later. However on-demand workflow specific specifications are called out for some interfaces | No |
| SCTE-35 | Defines 35 as the mandatory splice signalling mechanism, directly provides translations to various components and signals in workflows | Defines 35 as one of many possibilities for opportunity signals, but defines this interface as a broader concept IF-3. Where pieces interact with this interface 35 examples are properly given. Only absent example is `emsg` in-band SCTE, but this was a conscious omission | Text is parity where necessary, should `emsg` usage be brought in? |
| Tracking/Reporting | IAB Vast for reporting, DASH Callback for time based reporting | Parity text for IF-6, further elaboration for tracking via IF-8 | No |
| Remote Periods | The 4.3 text is structured to heavily rely on remote periods and provides assumptions/restrictions on usage | The CR text omits usage of remote periods in SSAI instead simplifying the architecture to not need it and calling out remote periods as part of the SGAI solution that will be detailed as follow up | No |
| Asset Identifier | The 4.3 text encourages identification of different assets via the asset identifier and provides various schemes for doing so | The CR text makes no mention or reference of identification of assets | Should identification be ported or referenced in other IOP sections? |

So the four main questions:
- Should we explicitly state the omission of CSAI?
- Should we port the `emsg` inband SCTE-35 example graphic
- Should we bring in and/or reference AssetIdentification information?

**Comment by haudiobe** [comment]
(2019/12/10 Pre-Meeting) 
On Q1: Yes
On Q2: we can, but not the primary workflow.
On Q3: Carry over - add to MPD towards the client.

**Comment by technogeek00** [comment]
Updates:

1. CSAI called out in introduction as a Note (1.1.3)
2. As part of #57 we reaffirmed not including `emsg`, I'd argue bringing in the graphic would be more confusing than helpful and as such I suggest we don't port it
3. Brought into Table 1/2/3 and descriptive paragraphs for 1/2
